default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DATABASE_USERNAME") %>
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") %>
  port: <%= ENV.fetch("RAILS_DATABASE_PORT") %>
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

development:
  <<: *default
  database: depot_development

test:
  <<: *default
  database: depot_test

production:
  primary: &primary_production
    <<: *default
    database: depot_production
  cache:
    <<: *primary_production
    database: depot_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: depot_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: depot_production_cable
    migrations_paths: db/cable_migrate
