name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_DOMAIN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ vars.DOCKER_REGISTRY_DOMAIN }}/${{ vars.DOCKER_IMAGE_NAME }}:production
          cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_DOMAIN }}/${{ vars.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY_DOMAIN }}/${{ vars.DOCKER_IMAGE_NAME }}:buildcache,mode=max

  deploy:
    runs-on: [self-hosted, linux, arm64]
    needs: build

    steps:
      - name: Make request to webhook
        env:
          DEPLOY_WEBHOOK: ${{ vars.DEPLOY_WEBHOOK }}
        run: curl -X POST $DEPLOY_WEBHOOK
